# Generated by Django 4.2.5 on 2023-11-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_usersignup_delete_usersigup'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('uno', models.IntegerField(primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('usalary', models.IntegerField()),
            ],
        ),
    ]
