# Generated by Django 4.2.5 on 2023-11-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_usersign_delete_usersignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('user_password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.DeleteModel(
            name='UserSign',
        ),
    ]
