# Generated by Django 5.0.6 on 2026-06-17 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField(blank=True)),
                ('resume_snapshot', models.FileField(blank=True, null=True, upload_to='application_resumes/')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('review', 'In Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('hired', 'Hired')], default='applied', max_length=20)),
                ('recruiter_notes', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
    ]
